FROM python:3.13-trixie

RUN curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc \
    && chmod a+r /etc/apt/keyrings/docker.asc \
    && echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian   trixie stable" > /etc/apt/sources.list.d/docker.list \
    && apt-get update -qq \
    && apt-get install -qq docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin \
    && rm -rf /var/lib/apt/lists/*

RUN pip install ansible==11.0 docker "molecule-plugins[docker]" yamllint ansible-lint
WORKDIR /ansible

ENTRYPOINT ["/bin/bash", "-c"]
CMD ["ansible --version"]

# build with : docker build . -f <thisfile> -t docker-ansible -t docker-ansible:1.0
# run with : docker run -it --rm -v -v "/var/run/docker.sock:/var/run/docker.sock" -v $PWD:/ansible docker-ansible bash
